default:
	echo 'nothing to do as default'
node-version:
	node -v
yarn-init:
	yarn add -D truffle
	yarn add -D typechain
	yarn add -D @typechain/web3-v1
	yarn add -D jest @types/jest
	yarn add -D @types/web3
	yarn add -D @types/node
	yarn add -D ts-node
	yarn add -D ts-jest
	yarn add -D @openzeppelin/contracts@4.4.0
	yarn -D add vue-property-decorator vue-class-component @nuxt/typescript-build @nuxt/types @types/lodash
	yarn -D add @babel/eslint-parser eslint eslint-plugin-nuxt eslint-plugin-vue
	yarn -D add node-sass@4.14.1
	yarn -D add @nuxtjs/vuetify
	yarn add web3
	yarn add bn.js
	yarn add nuxt core-js lodash vue-sweetalert2
nuxt-build:
	yarn build